extends Node
## TPS / FRAME PROFILER — ranks what actually costs us, by A/B/A measurement.
##
## Performance monitors give TOTALS, not attribution: "_process is 44 ms" doesn't say which
## of forty subsystems spent it. So measure it: switch ONE subsystem off, measure, switch it
## back. Two independent sweeps —
##   SCRIPT sweep : process_mode = DISABLED   (stops ticking, still drawn)
##   RENDER sweep : visible = false           (stops drawing, still ticking)
## — so "expensive to think about" is separated from "expensive to draw".
##
## THREE THINGS THE FIRST VERSION GOT WRONG, all of which produced confident nonsense
## (disabling PowerGrid, which does nothing per frame, "saved" -1.66 ms):
##
##  1. ONE BASELINE FOR THE WHOLE RUN. Frame time drifts as the world runs — the sun moves,
##     shadow cascades change, squalls arrive, fauna swim in and out of frame. Every sample
##     was compared against a baseline measured a minute earlier, so the table was ranking
##     drift. Now each target is measured ON / OFF / ON and the cost is the mean of the two
##     ON windows minus the OFF window, which cancels slow drift.
##  2. MEAN OF FRAME TIMES. One 250 ms hitch swamps a 45-frame mean. Now the MEDIAN.
##  3. TESTING NODES THAT CANNOT HAVE SCRIPT COST. A DirectionalLight3D has no script, so
##     "disabling" it can only measure noise — yet it ranked third. The script sweep now
##     only tests nodes that actually carry a script (plus autoloads).
##
## The world is also FROZEN for the run: GameClock and the storm are parked so lighting and
## weather cannot change underneath the measurement. Both are then measured on their own.
##
## VSYNC IS FORCED OFF — with it on every sample pins to the refresh interval.
##
## Run WINDOWED (rendering monitors read 0 headless):
##   godot --path . res://tests/tps_profile.tscn

const WARMUP_SEC: float = 32.0     ## past render_budget's 8 streaming sweeps
const SETTLE_FRAMES: int = 10
const SAMPLE_FRAMES: int = 31      ## odd, so the median is a real sample
## Subsystems worth breaking down per-species after the top-level sweep.
const DRILL: Array = ["bloom_fauna", "underwater_world"]

enum Phase { WARMUP, RUN, DONE }

var _phase: int = Phase.WARMUP
var _t: float = 0.0
var _main: Node
var _jobs: Array = []              ## [{name, node, mode:"script"|"render"}]
var _job: int = 0
var _step: int = 0                 ## 0 = ON(a1), 1 = OFF(b), 2 = ON(a2)
var _settle: int = 0
var _frames: Array = []
var _draws: Array = []
var _win: Array = []               ## the three windows' medians for this job
var _win_draw: Array = []
var _rows: Array = []
var _baseline_ms: float = 0.0
var _baseline_draw: float = 0.0

func _ready() -> void:
	DisplayServer.window_set_vsync_mode(DisplayServer.VSYNC_DISABLED)
	Engine.max_fps = 0
	var packed: PackedScene = load("res://scenes/Main.tscn")
	add_child(packed.instantiate())
	print("[tps] warming up %.0fs, then A/B/A per subsystem…" % WARMUP_SEC)

## Freeze anything that changes the scene's cost on its own while we measure.
func _freeze_world() -> void:
	for n in get_tree().root.get_children():
		if str(n.name) == "GameClock":
			n.process_mode = Node.PROCESS_MODE_DISABLED
	var storm: Node = _main.get("storm")
	if storm != null and is_instance_valid(storm):
		storm.process_mode = Node.PROCESS_MODE_DISABLED
	print("[tps] world frozen (clock + storm parked) so lighting/weather hold still")

## A readable identity: the SCRIPT is what tells you which subsystem this is — the node
## names are autogenerated (@Node3D@8019) because every subsystem is built in code.
func _label(n: Node) -> String:
	var s: Script = n.get_script()
	if s != null and s.resource_path != "":
		return s.resource_path.get_file().get_basename()
	return "%s(%s)" % [str(n.name), n.get_class()]

func _has_script_deep(n: Node, depth: int = 2) -> bool:
	if n.get_script() != null:
		return true
	if depth <= 0:
		return false
	for c in n.get_children():
		if _has_script_deep(c, depth - 1):
			return true
	return false

func _build_jobs() -> void:
	# Find Main EXPLICITLY by its script. An earlier version looked for the child with NO
	# script, which is backwards (Main carries main.gd), fell through to a guess, and
	# silently profiled nothing but the autoloads — 11 rows that all looked plausible.
	_main = get_child(0)
	for c in get_children():
		var s: Script = c.get_script()
		if s != null and String(s.resource_path).ends_with("main.gd"):
			_main = c
			break
	print("[tps] main scene = %s (%d children)" % [str(_main.name), _main.get_child_count()])
	# SCRIPT sweep: autoloads + any child of Main that carries a script.
	for n in get_tree().root.get_children():
		if n == self or n is Window:
			continue
		_jobs.append({"name": "autoload/" + str(n.name), "node": n, "mode": "script"})
	for n in _main.get_children():
		if _has_script_deep(n):
			_jobs.append({"name": _label(n), "node": n, "mode": "script"})
	# RENDER sweep: every visible Node3D child of Main, plus the lights/env, since the
	# directional shadow pass is a prime suspect.
	for n in _main.get_children():
		if n is Node3D and (n as Node3D).visible:
			_jobs.append({"name": _label(n), "node": n, "mode": "render"})
	# DRILL: the subsystem-level table says "bloom_fauna costs 8 ms" without saying which of
	# its forty creatures spent it. Toggle each SPECIES (all instances of one script at once,
	# since there are six crabs and three snails) so the table names the actual offender.
	for parent_name in DRILL:
		for n in _main.get_children():
			if _label(n) != parent_name:
				continue
			var by_script: Dictionary = {}
			for c in n.get_children():
				var key: String = _label(c)
				if not by_script.has(key):
					by_script[key] = []
				(by_script[key] as Array).append(c)
			for key in by_script:
				var group: Array = by_script[key]
				_jobs.append({"name": "%s > %s x%d" % [parent_name, key, group.size()],
					"nodes": group, "mode": "drill"})

func _process(delta: float) -> void:
	match _phase:
		Phase.WARMUP:
			_t += delta
			if _t < WARMUP_SEC:
				return
			_build_jobs()
			_freeze_world()
			print("[tps] %d measurements queued" % _jobs.size())
			_start_window()
			_phase = Phase.RUN
		Phase.RUN:
			if not _sample(delta):
				return
			_end_window()
		Phase.DONE:
			pass

func _start_window() -> void:
	_settle = SETTLE_FRAMES
	_frames.clear()
	_draws.clear()

func _sample(delta: float) -> bool:
	if _settle > 0:
		_settle -= 1
		return false
	_frames.append(delta * 1000.0)
	_draws.append(Performance.get_monitor(Performance.RENDER_TOTAL_DRAW_CALLS_IN_FRAME))
	return _frames.size() >= SAMPLE_FRAMES

func _median(a: Array) -> float:
	var b: Array = a.duplicate()
	b.sort()
	return float(b[b.size() / 2])

func _toggle(job: Dictionary, on: bool) -> void:
	# A drill job owns MANY nodes (every instance of one species), toggled together.
	if job.has("nodes"):
		for x in (job["nodes"] as Array):
			if is_instance_valid(x):
				(x as Node).process_mode = Node.PROCESS_MODE_INHERIT if on else Node.PROCESS_MODE_DISABLED
		return
	var n: Node = job["node"]
	if not is_instance_valid(n):
		return
	if job["mode"] == "script":
		n.process_mode = Node.PROCESS_MODE_INHERIT if on else Node.PROCESS_MODE_DISABLED
	elif n is Node3D:
		(n as Node3D).visible = on

func _end_window() -> void:
	_win.append(_median(_frames))
	_win_draw.append(_median(_draws))
	var job: Dictionary = _jobs[_job]
	if _step == 0:
		_toggle(job, false)          # -> OFF window
		_step = 1
		_start_window()
		return
	if _step == 1:
		_toggle(job, true)           # -> ON again
		_step = 2
		_start_window()
		return
	# three windows done
	var on_ms: float = (_win[0] + _win[2]) * 0.5
	var off_ms: float = _win[1]
	var on_draw: float = (_win_draw[0] + _win_draw[2]) * 0.5
	var off_draw: float = _win_draw[1]
	_rows.append({"name": job["name"], "mode": job["mode"],
		"saved": on_ms - off_ms, "draw": on_draw - off_draw,
		"noise": absf(_win[0] - _win[2])})
	if _baseline_ms <= 0.0:
		_baseline_ms = on_ms
		_baseline_draw = on_draw
		print("[tps] baseline %.2f ms (%.1f fps), %.0f draw calls"
			% [_baseline_ms, 1000.0 / maxf(_baseline_ms, 0.001), _baseline_draw])
	_win.clear()
	_win_draw.clear()
	_step = 0
	_job += 1
	if _job >= _jobs.size():
		_report()
		return
	_start_window()

func _report() -> void:
	_phase = Phase.DONE
	print("\n\n================ TPS PROFILE ================")
	print("baseline: %.2f ms/frame (%.1f fps), %.0f draw calls"
		% [_baseline_ms, 1000.0 / maxf(_baseline_ms, 0.001), _baseline_draw])
	print("'noise' is the spread between this row's two ON windows — a cost smaller than")
	print("its own noise figure is not a measurement, it is drift. Ignore those rows.")
	for mode in ["script", "render", "drill"]:
		var rows: Array = _rows.filter(func(r): return r["mode"] == mode)
		rows.sort_custom(func(a, b): return a["saved"] > b["saved"])
		print("\n--- %s COST — ms/frame recovered when switched off ---"
			% {"script": "SCRIPT (process_mode)", "render": "RENDER (visible=false)", "drill": "PER-SPECIES (process_mode)"}[mode])
		print("      ms    %%frame   draw calls   noise    subsystem")
		for r in rows:
			var trust: String = "  " if absf(r["saved"]) > r["noise"] else " ?"
			print("%s %7.2f  %5.1f%%  %9.0f  %6.2f    %s"
				% [trust, r["saved"], 100.0 * r["saved"] / maxf(_baseline_ms, 0.001),
					r["draw"], r["noise"], r["name"]])
	print("\n('?' = below its own noise floor)")
	print("=============================================\n")
	get_tree().quit()
