extends Node
## VANTAGE FRAME TIME — the before/after ruler for optimisation work.
##
## tps_profile.gd answers "which subsystem owns the frame". This answers the other half:
## "did the change actually make the frame cheaper, at the places a player stands?" It
## parks the camera at a fixed list of vantages, samples, and prints a median per vantage
## — so the same script run before and after an edit is a like-for-like comparison.
##
## Why it is built the way it is (all three learned the expensive way in this repo):
##
##  1. VSYNC OFF. With it on, every sample quantises to the refresh interval and a 4 ms
##     win reads as zero.
##  2. MEDIAN, NEVER MEAN. One 250 ms hitch swamps a 41-frame mean.
##  3. A PUBLISHED NOISE FLOOR. Each vantage is visited ROUNDS times, round-robin, and the
##     spread between the rounds' medians is printed next to the result. A change smaller
##     than its vantage's own noise figure is not a result, it is thermal drift — this
##     machine drifts several fps over a run.
##
## The world is FROZEN (clock forced, storm parked, player process off) so lighting and
## weather cannot change underneath the measurement, and the tree is FORCE-UNPAUSED every
## frame: pause_menu.gd auto-pauses on focus-out, and a paused world still renders, so
## losing focus mid-run yields beautiful, stable, meaningless numbers.
##
## Run WINDOWED (--headless draws nothing and every render monitor reads 0):
##   godot --path . res://tests/VantagePerf.tscn

const WARMUP_SEC: float = 33.0    ## past render_budget's 8 streaming sweeps (t=24 s)
const SETTLE_FRAMES: int = 14     ## let visibility ranges + culling resolve after a jump
const SAMPLE_FRAMES: int = 41     ## odd, so the median is a real sample
const ROUNDS: int = 3             ## revisits per vantage; the spread across them is the noise

## [name, eye, look_at]. The eye is the CAMERA position (the player's eye is ~1.6 m above
## its origin — aiming from the node origin photographs the floor).
const SPOTS := [
	["deck_floodlit", Vector3(0.0, 20.0, -1.0), Vector3(14.0, 19.0, 7.0)],
	["ops_lookout", Vector3(26.0, 39.0, -2.0), Vector3(20.0, 38.0, 6.0)],
	["wet_deck", Vector3(16.0, 4.0, -19.0), Vector3(13.0, 3.5, -12.0)],
	["waterline", Vector3(0.0, 1.1, -17.0), Vector3(0.0, -2.0, -34.0)],
	["submerged_mid", Vector3(0.0, -5.0, -16.0), Vector3(0.0, -6.0, -34.0)],
	["submerged_deep", Vector3(-8.0, -12.0, -6.0), Vector3(8.0, -13.0, 6.0)],
]

enum Phase { WARMUP, RUN, SWEEP, DONE }

var _phase: int = Phase.WARMUP
var _t: float = 0.0
var _main: Node
var _player: Node3D
var _cam: Camera3D
var _round: int = 0
var _spot: int = 0
var _settle: int = 0
var _frames: Array = []
var _procs: Array = []
var _draws: Array = []
var _prims: Array = []
## name -> [{ms, proc, draw, prim}] one entry per round
var _res: Dictionary = {}
## SWEEP: [{vantage, name, kind}] — one A/B/A per toggle per vantage.
var _jobs: Array = []
var _job: int = 0
var _step: int = 0                ## 0 = ON, 1 = OFF, 2 = ON again
var _win_ms: Array = []
var _sweep_rows: Array = []
var _reef: Node3D = null

func _ready() -> void:
	DisplayServer.window_set_vsync_mode(DisplayServer.VSYNC_DISABLED)
	Engine.max_fps = 0
	_main = load("res://scenes/Main.tscn").instantiate()
	add_child(_main)
	print("[vantage] warming up %.0f s, then %d vantages x %d rounds…" % [WARMUP_SEC, SPOTS.size(), ROUNDS])

func _freeze_world() -> void:
	GameClock.force_phase(GameClock.Phase.DAY)
	for n in get_tree().root.get_children():
		if str(n.name) == "GameClock":
			n.process_mode = Node.PROCESS_MODE_DISABLED
	var storm: Node = _main.get("storm")
	if storm != null and is_instance_valid(storm):
		storm.process_mode = Node.PROCESS_MODE_DISABLED
	_player = get_tree().get_first_node_in_group("player")
	_player.set_physics_process(false)
	_player.set_process(false)
	_cam = _player.get_node("Head/Camera3D")
	_cam.current = true
	var hud: Node = get_tree().get_first_node_in_group("hud")
	if hud:
		hud.set("visible", false)
	_reef = _find_script(_main, "leg_reef.gd") as Node3D
	print("[vantage] world frozen (clock DAY + parked, storm parked, player process off)")
	print("[vantage] leg reef: %s" % ("found" if _reef != null else "NOT PRESENT"))

## Find a node by the file its script came from — the world is built in code, so node names
## are autogenerated and the script IS the identity.
func _find_script(root: Node, frag: String) -> Node:
	var stack: Array = [root]
	while not stack.is_empty():
		var n: Node = stack.pop_back()
		for c in n.get_children():
			stack.append(c)
		var sc: Script = n.get_script()
		if sc != null and String(sc.resource_path).ends_with(frag):
			return n
	return null

## Flip one sweep target. Toggles are chosen so each isolates ONE question: what is the AI
## decimation actually buying at this vantage, and what is the new leg reef actually costing.
func _toggle(kind: String, on: bool) -> void:
	match kind:
		"ai_decimation":
			AiBudget.enabled = on
		"leg_reef":
			if _reef != null:
				_reef.visible = on

func _place(s: Array) -> void:
	_player.global_position = (s[1] as Vector3) - Vector3(0.0, 1.6, 0.0)
	_cam.global_position = s[1]
	_cam.look_at(s[2], Vector3.UP)

func _process(delta: float) -> void:
	# pause_menu auto-pauses on focus-out; a paused world still renders.
	if get_tree().paused:
		get_tree().paused = false
	match _phase:
		Phase.WARMUP:
			_t += delta
			if _t < WARMUP_SEC:
				return
			_freeze_world()
			_phase = Phase.RUN
			_place(SPOTS[0])
			_start()
		Phase.RUN:
			if _settle > 0:
				_settle -= 1
				return
			_frames.append(delta * 1000.0)
			_procs.append(Performance.get_monitor(Performance.TIME_PROCESS) * 1000.0)
			_draws.append(Performance.get_monitor(Performance.RENDER_TOTAL_DRAW_CALLS_IN_FRAME))
			_prims.append(Performance.get_monitor(Performance.RENDER_TOTAL_PRIMITIVES_IN_FRAME))
			if _frames.size() < SAMPLE_FRAMES:
				return
			_record()
		Phase.SWEEP:
			if _settle > 0:
				_settle -= 1
				return
			_frames.append(delta * 1000.0)
			_draws.append(Performance.get_monitor(Performance.RENDER_TOTAL_DRAW_CALLS_IN_FRAME))
			if _frames.size() < SAMPLE_FRAMES:
				return
			_sweep_step()
		Phase.DONE:
			pass

func _start() -> void:
	_settle = SETTLE_FRAMES
	_frames.clear()
	_procs.clear()
	_draws.clear()
	_prims.clear()

func _median(a: Array) -> float:
	var b: Array = a.duplicate()
	b.sort()
	return float(b[b.size() / 2])

func _record() -> void:
	var name: String = SPOTS[_spot][0]
	if not _res.has(name):
		_res[name] = []
	(_res[name] as Array).append({
		"ms": _median(_frames), "proc": _median(_procs),
		"draw": _median(_draws), "prim": _median(_prims)})
	_spot += 1
	if _spot >= SPOTS.size():
		_spot = 0
		_round += 1
		if _round >= ROUNDS:
			_report()
			_begin_sweep()
			return
	_place(SPOTS[_spot])
	_start()

## THE ATTRIBUTION HALF. The vantage table above says what the frame costs today; it cannot
## say what any one change is worth, because the only honest comparison — the same build,
## the same content, the same thermal state — is impossible across two runs an hour apart.
## (This mattered here: a 560-instance coral reef landed between the before and after runs,
## so the plain table is measuring my optimisation AND somebody else's new content at once.)
## So each toggle is measured ON / OFF / ON in ONE session, at each vantage, and the spread
## between the two ON windows is published next to the result as that row's noise floor.
func _begin_sweep() -> void:
	for s in SPOTS:
		for kind in ["ai_decimation", "leg_reef"]:
			if kind == "leg_reef" and _reef == null:
				continue
			_jobs.append({"vantage": s, "kind": kind})
	print("\n[vantage] sweep: %d A/B/A measurements…" % _jobs.size())
	_phase = Phase.SWEEP
	_job = 0
	_step = 0
	_win_ms.clear()
	_place(_jobs[0]["vantage"])
	_start()

func _sweep_step() -> void:
	_win_ms.append(_median(_frames))
	var job: Dictionary = _jobs[_job]
	if _step == 0:
		_toggle(job["kind"], false)
		_step = 1
		_start()
		return
	if _step == 1:
		_toggle(job["kind"], true)
		_step = 2
		_start()
		return
	var on_ms: float = (_win_ms[0] + _win_ms[2]) * 0.5
	_sweep_rows.append({"vantage": job["vantage"][0], "kind": job["kind"],
		"cost": on_ms - _win_ms[1], "on": on_ms, "noise": absf(_win_ms[0] - _win_ms[2])})
	_win_ms.clear()
	_step = 0
	_job += 1
	if _job >= _jobs.size():
		_report_sweep()
		return
	_place(_jobs[_job]["vantage"])
	_start()

func _report_sweep() -> void:
	_phase = Phase.DONE
	print("\n=========== WHAT EACH THING COSTS, PER VANTAGE ===========")
	print("ms recovered when the thing is switched OFF, measured ON/OFF/ON in one session.")
	print("'noise' is this row's own spread between its two ON windows — a cost smaller")
	print("than its own noise figure is drift, not a measurement.")
	print("%-16s %-14s %9s %9s %8s %8s" % ["vantage", "thing", "ms saved", "of ms", "%", "noise"])
	for r in _sweep_rows:
		var trust: String = "  " if absf(r["cost"]) > r["noise"] else " ?"
		print("%s %-14s %-14s %9.2f %9.2f %7.1f%% %8.2f"
			% [trust, r["vantage"], r["kind"], r["cost"], r["on"],
				100.0 * r["cost"] / maxf(r["on"], 0.001), r["noise"]])
	print("\n('?' = below its own noise floor)")
	print("ai_decimation OFF means every creature ticks every frame — the pre-change")
	print("behaviour. leg_reef OFF means the new coral is not drawn.")
	print("=========================================================\n")
	get_tree().quit()

func _report() -> void:
	_phase = Phase.DONE
	print("\n\n================ VANTAGE FRAME TIME ================")
	print("median of %d frames per visit, %d visits per vantage." % [SAMPLE_FRAMES, ROUNDS])
	print("'noise' = spread between this vantage's own repeat visits. A before/after")
	print("difference smaller than that figure is drift, not a result.")
	print("%-16s %8s %8s %8s %9s %11s" % ["vantage", "ms", "fps", "noise", "script ms", "draw calls"])
	for s in SPOTS:
		var name: String = s[0]
		var runs: Array = _res.get(name, [])
		if runs.is_empty():
			continue
		var ms: Array = []
		var pr: Array = []
		for r in runs:
			ms.append(r["ms"])
			pr.append(r["proc"])
		var med: float = _median(ms)
		var lo: float = ms.min()
		var hi: float = ms.max()
		print("%-16s %8.2f %8.1f %8.2f %9.2f %11.0f" % [name, med, 1000.0 / maxf(med, 0.001),
			hi - lo, _median(pr), float(runs[0]["draw"])])
	print("\nper-visit detail (ms):")
	for s in SPOTS:
		var name: String = s[0]
		var runs: Array = _res.get(name, [])
		if runs.is_empty():
			continue
		var parts: Array = []
		for r in runs:
			parts.append("%.2f" % float(r["ms"]))
		print("  %-16s %s   prims %.0f" % [name, ", ".join(parts), float(runs[0]["prim"])])
	print("===================================================")
