extends Node3D
## The wet deck's natural stock: what the sea leaves on the rig rather than what
## the crew did. Tar weeping out of the deck seams, barnacle crust up the caisson
## and along the lip where the swell washes over, floats snagged in the dock
## fenders, kelp growing on the plates, and the old fish-cleaning board under the
## drying lines.
##
## All of these are Salvage nodes with a regrow time: unlike a gutted locker they
## come back if you leave them alone, so the rig keeps feeding you slowly instead
## of being mined out on day one. The floats are the exception — a float is an
## object, and once you've cut it free it's yours.
##
## Everything sits on the wet deck (floor y = 2.0, x 8..30, z -22..2), on the
## SE caisson's west face (x = 19, z -15..-9), which is the only leg that comes up
## through this deck, and — the kelp only — on the open south pontoon west of x 8.
##
## TWO CLOCKS, BOTH ON THE CALENDAR (2026-08-08). Every regrow time in this file used to be a
## countdown in REAL seconds, which is blind to sleep, so nothing here grew back overnight —
## see the ladder of constants below. And regrowth alone only ever returns what the player has
## already found: the kelp additionally SPAWNS NEW STANDS on a game-hour interval up to a
## density cap, from a candidate pool measured once at world build. See _kelp_growth().
##
## GLOW WORM CLUSTERS (2026-07-27) are the newest of these and the one that feeds another
## system rather than the crafting bench: they are the deep rig's best bait. See
## _glowworm_clusters() for where they sit and why, and fish_table.gd's BAIT_TABLE for what
## a glowing bait does on a hook.

const SALVAGE := preload("res://scripts/components/salvage.gd")
const WET_Y: float = 2.0

# ============================================================ how often it comes back
#
# ON THE CALENDAR, NOT ON A STOPWATCH (s47). Every node in this file used to count its
# regrowth in REAL seconds — 200-300 s of `delta`. That clock is blind to sleep: the one
# thing a player does to make time pass, `GameClock.skip_to_next_dawn()`, bumps the calendar
# a whole day and spends no real time at all, so kelp did NOT grow back overnight and never
# had. The owner's "it should come back over time" is exactly this bug. `Salvage` already
# knew how to count on the calendar for the five-day mussel beds, so the fix is these five
# numbers and the `regrow_hours` key that reads them.
#
# THE LADDER, and why each rung is where it is. One game day is 24 game hours = 3600 real
# seconds on the shipped phase plan (GameClock.real_sec_per_game_day), i.e. 150 real seconds
# a game hour. They are deliberately far apart so the rig teaches a rhythm rather than one
# undifferentiated cooldown: you learn that the kelp is back every morning and that the
# barnacles are a twice-a-week job.
#
#   kelp        6 h  — a quarter day. Kelp is the fastest-growing alga there is (a real
#                      Macrocystis puts on half a metre a day) and the Bloom is faster
#                      still, so a stand you cut at dawn is worth walking past at noon.
#   glow worms  9 h  — one night plus the dark either side of it. The brood repopulates a
#                      patch in the wet dark; that is a night's work, not a day's.
#   tar        18 h  — NOT biology. Tar is a rig artefact: cold bitumen weeping out of a
#                      deck seam under its own head. It does not grow, it seeps, and it
#                      seeps slowly — most of a day to make another lump's worth.
#   board      24 h  — exactly one day. Nothing grows on a cleaning board either; what
#                      refills it is a day of gulls, drying lines and fish frames.
#   barnacle   48 h  — two days, the slowest thing on the deck. Barnacle spat settles and
#                      then calcifies; a crust you scraped bare is a fortnight in the real
#                      world and two days here, which is as slow as this rig gets before a
#                      node stops reading as renewable at all.
#
# (Mussel beds are five days and live in mussel_beds.gd — the far end of the same ladder.)
const KELP_REGROW_H: float = 6.0
const GLOW_REGROW_H: float = 9.0
const TAR_REGROW_H: float = 18.0
const BOARD_REGROW_H: float = 24.0
const BARNACLE_REGROW_H: float = 48.0

## MatLib.flat() hands back a CACHED material — tuning roughness or emission on one
## would retune it everywhere that colour is used. These are ours alone.
var _m_tar: StandardMaterial3D
var _m_shell: StandardMaterial3D
var _m_kelp: StandardMaterial3D
var _m_bone: StandardMaterial3D

func _ready() -> void:
	name = "HarvestNodes"    # findable by a probe; the host used to take an autogenerated name
	# Tar stays wet-looking years cold — but "wet black" is a SPECULAR read, not a dark
	# albedo. At 0.045 albedo with middling roughness and no direct light under the deck
	# a seam photographed as a pure black ellipse: a hole in the plating, not tar.
	# The colour lifts just off black and the gloss goes right up, so it catches the sky.
	_m_tar = _mat(Color(0.085, 0.078, 0.072), 0.16)
	_m_tar.metallic_specular = 0.85
	_m_shell = _mat(Color(0.72, 0.7, 0.63), 0.9)
	_m_kelp = _mat(Color(0.12, 0.3, 0.24), 0.75)
	_m_kelp.emission_enabled = true
	_m_kelp.emission = Color(0.1, 0.55, 0.45)
	_m_kelp.emission_energy_multiplier = 0.25          # the Bloom is in everything down here
	_m_bone = _mat(Color(0.86, 0.84, 0.76), 0.8)
	_tar_seams()
	_barnacle_crust()
	_snagged_floats()
	_kelp_growth()
	_cleaning_board()
	_glowworm_clusters()

func _mat(color: Color, roughness: float) -> StandardMaterial3D:
	var m := StandardMaterial3D.new()
	m.albedo_color = color
	m.roughness = roughness
	return m

# ---- tar: the deck seams have been weeping since before the evacuation ----

func _tar_seams() -> void:
	var def := {
		"tools": [], "speed": ["prybar", "hand_file"], "verb": "SCRAPE", "work": 2.6,
		"sound": "hiss", "regrow_hours": TAR_REGROW_H, "name": "Tar Seam",
		"yields": {"tar_lump": 1},
		"hint": "", "start": "You lever up an edge of the tar.",
		"done": "It peels off the seam in a cold black lump.",
	}
	for spot in [Vector3(20.6, WET_Y, -6.2), Vector3(14.2, WET_Y, -4.4),
			Vector3(26.2, WET_Y, -9.6), Vector3(9.8, WET_Y, -2.6),
			Vector3(18.4, WET_Y, -14.4)]:
		SALVAGE.from_visual(self, _tar_visual(), spot, fmod(spot.x * 37.0, 360.0), def, 0.5)

func _tar_visual() -> Node3D:
	var root := Node3D.new()
	for i in range(3):
		var mi := MeshInstance3D.new()
		var cm := CylinderMesh.new()
		cm.top_radius = 0.16 + i * 0.09
		cm.bottom_radius = cm.top_radius
		cm.height = 0.018 + i * 0.004
		cm.material = _m_tar
		mi.mesh = cm
		mi.cast_shadow = GeometryInstance3D.SHADOW_CASTING_SETTING_OFF
		root.add_child(mi)
		mi.position = Vector3(cos(i * 2.4) * 0.11 * i, 0.012 + i * 0.004, sin(i * 2.4) * 0.11 * i)
	return root

# ---- barnacle and limpet crust: spray zone, so it never quite dries out ----

func _barnacle_crust() -> void:
	var def := {
		"tools": [], "speed": ["hammer_tool", "prybar"], "verb": "SCRAPE", "work": 2.2,
		"sound": "scuttle_c", "regrow_hours": BARNACLE_REGROW_H, "risk": 0.02,
		"name": "Barnacle Crust",
		"yields": {"shell_grit": 1},
		"hint": "", "start": "You get an edge under the crust.",
		"done": "A palmful of broken shell comes away with it.",
	}
	# Up the SE caisson's west face (leg spans x 19..25, z -15..-9).
	for spot in [Vector3(18.93, WET_Y + 0.35, -13.4), Vector3(18.93, WET_Y + 0.6, -12.0),
			Vector3(18.93, WET_Y + 0.2, -10.6)]:
		SALVAGE.from_visual(self, _crust_visual(true), spot, 0.0, def, 0.4)
	# And along the seaward lip by the dock, where the swell comes over.
	for spot in [Vector3(23.6, WET_Y + 0.06, -21.8), Vector3(10.6, WET_Y + 0.06, -21.8)]:
		SALVAGE.from_visual(self, _crust_visual(false), spot, 0.0, def, 0.4)

func _crust_visual(wall: bool) -> Node3D:
	var root := Node3D.new()
	for i in range(9):
		var mi := MeshInstance3D.new()
		var cone := CylinderMesh.new()
		cone.top_radius = 0.008 + fmod(i * 0.013, 0.012)
		cone.bottom_radius = 0.024 + fmod(i * 0.019, 0.018)
		cone.height = 0.03 + fmod(i * 0.011, 0.025)
		cone.material = _m_shell
		mi.mesh = cone
		mi.cast_shadow = GeometryInstance3D.SHADOW_CASTING_SETTING_OFF
		root.add_child(mi)
		var a: float = i * 2.399963
		var r: float = 0.035 + 0.02 * (i % 4)
		if wall:
			# Growing OUT of a vertical face: barnacles lie on their sides.
			mi.position = Vector3(0.012, cos(a) * r, sin(a) * r)
			mi.rotation.z = deg_to_rad(90.0)
		else:
			mi.position = Vector3(cos(a) * r, 0.015, sin(a) * r)
	return root

# ---- floats torn off someone else's gear and caught in our fenders ----

func _snagged_floats() -> void:
	var def := {
		"tools": [], "speed": ["crude_knife"], "verb": "CUT FREE", "work": 1.8,
		"sound": "hiss", "name": "Snagged Float",
		# The done-text has always said it comes away "still trailing a foot of someone
		# else's rope" — so it hands you the rope too. Untying a float on the wet deck is
		# one of the first things a player does; it should stock the first craft.
		"yields": {"float_buoy": 1, "rope": 1},
		"hint": "", "start": "You start working the line off the cleat.",
		"done": "The float comes free, still trailing a foot of someone else's rope.",
	}
	var tints := [Color(0.85, 0.32, 0.16), Color(0.9, 0.78, 0.2), Color(0.2, 0.45, 0.7)]
	var spots := [Vector3(16.6, WET_Y + 0.35, -21.9), Vector3(22.6, WET_Y + 0.35, -21.9),
			Vector3(24.8, WET_Y + 0.2, -21.6)]
	for i in range(spots.size()):
		SALVAGE.from_visual(self, _float_visual(tints[i]), spots[i], i * 55.0, def, 0.35)

func _float_visual(tint: Color) -> Node3D:
	var root := Node3D.new()
	var ball := MeshInstance3D.new()
	var sm := SphereMesh.new()
	sm.radius = 0.17
	sm.height = 0.36
	sm.material = MatLib.flat(tint)
	ball.mesh = sm
	root.add_child(ball)
	ball.position = Vector3(0, 0.17, 0)
	# A MOULDED SEAM AND A HAULING EYE, because a bare tinted sphere reads as a placeholder.
	# Found 2026-07-29 by the same screen-pixel hunt that caught the fender posts and the
	# line-throwing box (tests/SpawnYellow.tscn): the yellow one of these three is a 0.34 m
	# blob of `MatLib.flat(Color(0.9, 0.78, 0.2))` and it was the largest saturated-yellow
	# blob on the wet deck after the box was fixed — 6.9 m off the Dock Locker, right at the
	# fender frame. It is NOT the box the owner reported and it is real, interactable salvage
	# (CUT FREE -> float_buoy + rope), so it keeps its colour: a trawl float genuinely is one
	# flat bright plastic colour. What it was missing is any evidence of manufacture. Two
	# parts fix that and neither touches the collider SALVAGE.from_visual builds.
	var seam := MeshInstance3D.new()
	var seam_m := TorusMesh.new()
	seam_m.inner_radius = 0.166
	seam_m.outer_radius = 0.178
	seam_m.rings = 20
	seam_m.ring_segments = 8
	seam_m.material = MatLib.flat(tint.darkened(0.38))
	seam.mesh = seam_m
	seam.cast_shadow = GeometryInstance3D.SHADOW_CASTING_SETTING_OFF
	root.add_child(seam)
	seam.position = Vector3(0, 0.17, 0)
	seam.rotation.x = deg_to_rad(90)                     # the mould line round the equator
	var eye := MeshInstance3D.new()
	var eye_m := TorusMesh.new()
	eye_m.inner_radius = 0.018
	eye_m.outer_radius = 0.036
	eye_m.rings = 16
	eye_m.ring_segments = 8
	eye_m.material = MatLib.galvanized()
	eye.mesh = eye_m
	eye.cast_shadow = GeometryInstance3D.SHADOW_CASTING_SETTING_OFF
	root.add_child(eye)
	eye.position = Vector3(0, 0.36, 0)                   # the eye the line is bent onto
	# The tail of line it came in on, coiled where it fell.
	var line := MeshInstance3D.new()
	var tm := TorusMesh.new()
	tm.inner_radius = 0.07
	tm.outer_radius = 0.11
	tm.material = MatLib.rope_mat()
	line.mesh = tm
	line.cast_shadow = GeometryInstance3D.SHADOW_CASTING_SETTING_OFF
	root.add_child(line)
	line.position = Vector3(0.14, 0.02, 0.06)
	return root

# ============================================================ kelp on the open pontoon
#
# THE BLOOM GROWS ON ANYTHING THAT STAYS WET, and this is the one place on the rig that does
# while still being open to the sky and standing on.
#
# WHAT WAS WRONG (s47, measured — tests/HarvestGrowthProbe.tscn re-measures it every run).
# The four kelp stands shipped as hand-typed Y literals, and all four were wrong:
#
#     authored (28.80, 0.95, -20.40)   column below it: y 3.00 bollard, y 2.00 deck. NOTHING
#     authored ( 8.50, 0.95, -14.20)   y 2.00 deck, then y 0.95 pontoon        <- seated
#     authored (28.90, 0.55,  -1.40)   y 2.00 deck. NOTHING below
#     authored ( 8.50, 0.55,  -5.60)   y 2.00 deck. NOTHING below
#
# Three of the four were fronds growing out of thin air, and the fourth was seated on the
# pontoon 1.05 m UNDER the wet-deck slab. rig_builder.gd:4241-4246 spells out why that is not
# a place at all: the slab is a single box over x 8..30, z -22..2, its soffit is y 1.5 and the
# pontoon top is y 0.95, so everything the old comment called "the splash zone" is a 0.55 m
# roofed crawl space with no view of the water. The one open, sunlit, wave-washed deck on this
# rig is the SOUTH PONTOON WEST OF x 8 — the same reason the tide staff and the Pontoon Ladder
# both stand there. Measured clear at 0.95 across x 3.6..7.6, z -16.0..-8.0, one unbroken
# slab, no dressing on it.
#
# So the stands moved onto that dock, and NO Y IS TYPED any more: only XZ is authored and the
# seat is a downward raycast, refused unless it lands flat, inside the splash band, clear of
# the ladder and clear of its neighbours. The band check is precisely the assertion that would
# have caught the four above — the deck plate answers at y 2.00 and 2.00 is not in the band.
#
# NB this MOVES four shipping nodes, so their position-keyed save entries
# (save_manager.gd:460) no longer match. The only consequence is that a kelp stand harvested
# before the move comes back grown in a save loaded after it, which is the generous direction.

## AUTHORED IN XZ ONLY — the Y comes off the raycast. Ten candidates for a cap of eight, so a
## spot that is refused (a crate lands there, a crab is standing on it) costs a spare rather
## than a stand. Laid out on a jittered 3-column lattice over the open slab with no pair
## closer than 1.41 m, all of them >2.2 m off the Pontoon Ladder's landing at (7.8, -12).
const KELP_SPOTS: Array[Vector2] = [
	Vector2(4.2, -15.3), Vector2(5.7, -14.4), Vector2(7.0, -15.1), Vector2(4.1, -13.2),
	Vector2(5.6, -12.2), Vector2(4.3, -11.0), Vector2(5.9, -10.3), Vector2(3.9, -8.8),
	Vector2(7.1, -9.0), Vector2(5.3, -8.6),
]
## The probe. Fired from above the pontoon but BELOW the wet-deck slab's own top, and the
## accepted band is the tidal splash zone: the tide runs -0.7..+0.7 (rig_builder.TIDE_BOARD),
## the pontoon deck is 0.95, and the deck plate above it is 2.00 — which the band refuses.
const KELP_PROBE_TOP: float = 1.9
const KELP_PROBE_BOTTOM: float = -1.5
const KELP_BAND_LO: float = 0.4
const KELP_BAND_HI: float = 1.6
## A kelp seat has to be a floor, not a bollard shoulder or an animal's touch sphere. Same
## test mussel_beds.FACE_ALIGN_MIN makes against a caisson face, for the same reason.
const KELP_FLAT_MIN: float = 0.985
## No two stands closer than this, so they read as separate stands you cut one at a time.
const KELP_SPACING: float = 1.3
## Hands off the Pontoon Ladder's landing (rig_builder._build_access) — the only way down
## here, and a 0.45 m interaction box across its foot would be a daily annoyance.
const KELP_LADDER := Vector2(7.8, -12.0)
const KELP_LADDER_CLEAR: float = 1.5

## HOW MANY, AND HOW OFTEN NEW ONES TAKE HOLD.
##
## The opening stock is four, exactly as it shipped, so a new game looks the way it did. From
## there the dock fills in: one more stand takes hold every KELP_SETTLE_H game hours until
## the cap. That is the half of "over time" that a regrow timer cannot give you — regrowth
## only ever puts back what you already found, and the owner asked for kelp that SPAWNS.
##
## The live count is a pure function of the calendar (opening + game_hours / interval, capped),
## which is what makes it safe against the position-keyed save: no new save field, a slot
## loaded on day 6 arrives at day 6's density, and every stand's position was fixed at world
## build whether it is standing yet or not. It only ever rises within a session.
const KELP_OPENING: int = 4
const KELP_CAP: int = 8
const KELP_SETTLE_H: float = 8.0
## How often the growth check runs, in real seconds. Nothing here is frame-sensitive: the
## smallest interval in the file is 6 game hours = 900 real seconds, so 4 s of granularity is
## three orders of magnitude finer than the thing it is watching and costs nothing.
const GROW_CHECK_SEC: float = 4.0

## Anything that is alive, harvestable or built gets excluded from the seat rays. This is the
## FaunaTouch trap in docs/AGENT_TRAPS.md, which bites placement code and not only probes: an
## Interactable is a StaticBody3D with a 0.6-0.85 m sphere on the default layer, so a crab on
## the pontoon is a "floor" at 1.5 m until it walks off and leaves the kelp hanging.
const SKIP_SCRIPTS := ["bloom_fauna.gd", "reef_life.gd", "reef_fish.gd", "leg_reef.gd",
	"mussel_beds.gd", "salvage.gd", "harvest_nodes.gd", "shark.gd", "crab.gd", "king_crab.gd",
	"ship_cat.gd", "jelly_glow.gd", "structures.gd", "player_controller.gd", "takeable.gd"]

var _kelp_plan: Array[Vector3] = []   ## probed seats, in the order they take hold
var _kelp_live: int = 0
var _grow_check: float = 0.0
var _kelp_refused := {"nothing": 0, "tilt": 0, "band": 0, "ladder": 0, "spacing": 0}

func _kelp_growth() -> void:
	# Physics is not queryable until a frame has run, and the animals that have to be skipped
	# are spawned by their own _ready calls — so the survey happens after the tree has ticked,
	# exactly as mussel_beds.gd does it.
	await get_tree().physics_frame
	await get_tree().physics_frame
	_kelp_survey()
	_grow_to_target()
	set_process(true)
	print("[kelp] %d stands up of %d planned seats (opening %d, cap %d, one more every %.0f game hours = %.0f real s) · refused %s"
		% [_kelp_live, _kelp_plan.size(), KELP_OPENING, KELP_CAP, KELP_SETTLE_H,
			KELP_SETTLE_H / 24.0 * GameClock.real_sec_per_game_day(), _kelp_refused])

func _kelp_def() -> Dictionary:
	return {
		"tools": [], "speed": ["crude_knife"], "verb": "GATHER", "work": 1.6,
		"sound": "hiss", "regrow_hours": KELP_REGROW_H, "name": "Kelp Growth",
		"yields": {"kelp_bundle": 1},
		"hint": "", "start": "",
		"done": "You strip an armful off the plate; it's cold and it faintly glows.",
	}

## Measure every candidate ONCE, at world build, and keep the ones that are really a wet deck.
## Doing the whole survey up front is what makes the timed spawning deterministic: a stand's
## position is decided here whether it takes hold on day 0 or day 6, so the save key it will
## eventually be written under is fixed before the player has done anything.
func _kelp_survey() -> void:
	var space: PhysicsDirectSpaceState3D = get_world_3d().direct_space_state
	if space == null:
		push_warning("[kelp] no physics space — the four opening stands cannot be seated")
		return
	var skip: Array[RID] = _skip_bodies()
	for xz in KELP_SPOTS:
		if _kelp_plan.size() >= KELP_CAP:
			break
		var q := PhysicsRayQueryParameters3D.create(Vector3(xz.x, KELP_PROBE_TOP, xz.y),
			Vector3(xz.x, KELP_PROBE_BOTTOM, xz.y))
		q.collision_mask = 1
		q.exclude = skip
		var hit: Dictionary = space.intersect_ray(q)
		if hit.is_empty():
			_kelp_refused["nothing"] += 1
			continue
		if (hit["normal"] as Vector3).normalized().dot(Vector3.UP) < KELP_FLAT_MIN:
			_kelp_refused["tilt"] += 1
			continue
		var seat: Vector3 = hit["position"]
		if seat.y < KELP_BAND_LO or seat.y > KELP_BAND_HI:
			_kelp_refused["band"] += 1
			continue
		if xz.distance_to(KELP_LADDER) < KELP_LADDER_CLEAR:
			_kelp_refused["ladder"] += 1
			continue
		var clash: bool = false
		for p in _kelp_plan:
			if Vector2(p.x, p.z).distance_to(xz) < KELP_SPACING:
				clash = true
				break
		if clash:
			_kelp_refused["spacing"] += 1
			continue
		_kelp_plan.append(seat)

func _skip_bodies() -> Array[RID]:
	var out: Array[RID] = []
	var root: Node = get_tree().current_scene
	if root == null:
		root = get_tree().root
	for node in root.find_children("*", "CollisionObject3D", true, false):
		var p: Node = node
		while p != null:
			var s: Script = p.get_script()
			if s != null and SKIP_SCRIPTS.has(String(s.resource_path).get_file()):
				out.append((node as CollisionObject3D).get_rid())
				break
			p = p.get_parent()
	return out

## How many stands the calendar says should be standing right now.
func kelp_target() -> int:
	var grown: int = KELP_OPENING + int(GameClock.game_time_hours() / KELP_SETTLE_H)
	return mini(mini(grown, KELP_CAP), _kelp_plan.size())

func _grow_to_target() -> void:
	var want: int = kelp_target()
	while _kelp_live < want:
		var seat: Vector3 = _kelp_plan[_kelp_live]
		SALVAGE.from_visual(self, _kelp_visual(), seat, fmod(seat.z * 23.0, 360.0),
			_kelp_def(), 0.45)
		_kelp_live += 1

func _process(delta: float) -> void:
	_grow_check -= delta
	if _grow_check > 0.0:
		return
	_grow_check = GROW_CHECK_SEC
	if _kelp_live >= mini(KELP_CAP, _kelp_plan.size()):
		set_process(false)     # the dock is full; nothing left to watch for
		return
	_grow_to_target()

func _kelp_visual() -> Node3D:
	var root := Node3D.new()
	for i in range(7):
		var mi := MeshInstance3D.new()
		var bm := BoxMesh.new()
		bm.size = Vector3(0.05 + fmod(i * 0.017, 0.03), 0.02, 0.34 + fmod(i * 0.09, 0.26))
		bm.material = _m_kelp
		mi.mesh = bm
		mi.cast_shadow = GeometryInstance3D.SHADOW_CASTING_SETTING_OFF
		root.add_child(mi)
		var a: float = i * 2.399963
		mi.position = Vector3(cos(a) * 0.07, 0.06 + (i % 3) * 0.05, sin(a) * 0.07)
		mi.rotation.y = a
		# Blades LEAN UP off the plate (55-80 deg) instead of lying flat: a frond reads
		# as growth, a flat slab reads as a dropped panel.
		mi.rotation.x = deg_to_rad(-55.0 - fmod(i * 17.0, 25.0))
	return root

# ---- the fish-cleaning board under the drying lines ----

func _cleaning_board() -> void:
	# Sits between the two hang lines strung at (13.0,-18.2) and (12.0,-20.5), on the
	# clear patch inside the drying-line posts at x 11.6 / 14.4.
	var def := {
		"tools": ["crude_knife"], "verb": "CLEAN", "work": 2.6,
		"sound": "hiss", "regrow_hours": BOARD_REGROW_H, "name": "Fish-Cleaning Board",
		"yields": {"fish_bone": 1},
		"hint": "the scraps are frozen to the board. A knife would lift them.",
		"start": "You set to work on what the last crew left.",
		"done": "You lift the frame clear of the board, picked clean.",
	}
	SALVAGE.from_visual(self, _board_visual(), Vector3(13.2, WET_Y, -19.4), 18.0, def, 0.6)

# ---- glow worm clusters: the Bloom's own light, and the deep rig's best bait ----
#
# NOT the same animal as bloom_fauna.GlowWorm. That one is a single skittish night-dweller
# that feels you coming and sinks into its den — you sneak up on it and GRAB it, one worm,
# once a night. This is the other half of the same species: the packed brood colonies that
# never leave the plate, in the permanently wet dark where nothing dries. You gather those
# by the handful, and the patch comes back.
#
# WHERE. Two habitats, both already proven clear of geometry by what is planted on them:
# the SE caisson's west face (the barnacle crust's own plane, x 18.93, at z values the
# crust does not use) and the wet-deck floor a metre off three of the colony's den mouths
# (bloom_fauna.GlowWormColony.DENS) — beside the dens, never on them, so the interaction
# ray is never choosing between a cluster and a live worm at the same point.
## The old GLOW_REGROW was 220 REAL seconds and its comment claimed "roughly a night-phase" —
## which it never was (NIGHT is 780 real seconds) and, being a `delta` countdown, it could not
## have been: a night the player SLEPT through spent none of it. GLOW_REGROW_H is the same
## intent stated on the clock that can actually see a night. See the ladder at the top.

func _glowworm_clusters() -> void:
	var def := {
		"tools": [], "speed": [], "verb": "GATHER", "work": 1.4,
		"sound": "hiss", "regrow_hours": GLOW_REGROW_H, "name": "Glow Worm Cluster",
		"yields": {"glow_worm": 1},   # re-rolled to 1-3 per growth — see GlowCluster below
		"hint": "", "start": "You cup a hand around the light.",
		"done": "They come away cold, curling, and still lit.",
	}
	# [position, is it growing out of a vertical face]
	var spots := [
		[Vector3(18.93, WET_Y + 0.45, -14.4), true],   # SE caisson west face, below the crust
		[Vector3(18.93, WET_Y + 0.8, -9.6), true],     # same face, up under the deck lip
		[Vector3(26.3, WET_Y, -5.0), false],           # stair-ramp shadow, off the den mouth
		[Vector3(17.7, WET_Y, -10.6), false],          # SE leg base, west of the steel
		[Vector3(11.5, WET_Y, -20.5), false],          # loot-room inner corner
	]
	for spot in spots:
		var vis := _glow_visual(bool(spot[1]), fmod(absf((spot[0] as Vector3).z) * 1.7, TAU))
		var node: Salvage = SALVAGE.from_visual(self, vis, spot[0],
			fmod((spot[0] as Vector3).x * 41.0, 360.0), def, 0.4)
		vis.bind(node)
		# Gathering a patch is also how a player who never crept up on a lone worm at night
		# learns what these are.
		node.interacted.connect(func(_v: String) -> void: Journal.discover("creature_glow_worm"))

## One patch: a dark wet smear of den mouths with the brood packed into it. Each cluster
## OWNS its material — MatLib.flat() and a shared local material would dim every patch on
## the rig the moment one of them was gathered.
func _glow_visual(wall: bool, phase: float) -> GlowCluster:
	var root := GlowCluster.new()
	root.phase = phase
	root.mat = StandardMaterial3D.new()
	root.mat.albedo_color = Color(0.16, 0.42, 0.4)
	root.mat.roughness = 0.55
	root.mat.emission_enabled = true
	root.mat.emission = Color(0.25, 0.95, 0.85)
	root.mat.emission_energy_multiplier = GlowCluster.LIT
	var damp := _mat(Color(0.06, 0.08, 0.08), 0.35)
	damp.metallic_specular = 0.8              # the wet patch they live in, catching light
	var patch := MeshInstance3D.new()
	var pm := CylinderMesh.new()
	pm.top_radius = 0.22
	pm.bottom_radius = 0.22
	pm.height = 0.015
	pm.material = damp
	patch.mesh = pm
	patch.cast_shadow = GeometryInstance3D.SHADOW_CASTING_SETTING_OFF
	root.add_child(patch)
	# The worms themselves: eleven short lit bodies at every angle out of the patch, so a
	# third of them coming off (Salvage._strip pulls meshes) still leaves a colony behind.
	for i in range(11):
		var mi := MeshInstance3D.new()
		var cm := CapsuleMesh.new()
		cm.radius = 0.018 + fmod(i * 0.007, 0.012)
		cm.height = 0.09 + fmod(i * 0.023, 0.08)
		cm.material = root.mat
		mi.mesh = cm
		mi.cast_shadow = GeometryInstance3D.SHADOW_CASTING_SETTING_OFF
		root.add_child(mi)
		var a: float = i * 2.399963
		var r: float = 0.045 + 0.028 * (i % 4)
		mi.position = Vector3(cos(a) * r, 0.035 + fmod(i * 0.019, 0.05), sin(a) * r)
		# Curled over on the plate, not standing up like candles.
		mi.rotation = Vector3(deg_to_rad(52.0 + fmod(i * 21.0, 40.0)), a, 0.0)
	if wall:
		# Growing out of a vertical face: the whole patch lies on its side.
		root.rotation.z = deg_to_rad(90.0)
	return root

## The live half of a cluster. Salvage already hides parts, soots what is left and heals it
## all again on regrow, but soot cannot take the LIGHT out of an emissive body — a gathered
## patch would have kept glowing exactly as brightly with a third of its worms missing. So
## this eases the emission down to embers while the node is spent and brings it back up as
## the brood regrows, and it is also where the 1-3 yield lives: the count is re-rolled on
## every regrowth, which keeps the grant inside Salvage's all-or-nothing pack check instead
## of bolting extra add_item() calls onto the end of it.
class GlowCluster extends Node3D:
	const LIT: float = 1.15
	const EMBERS: float = 0.1
	const FADE: float = 0.55        ## how fast the light follows the state, energy/sec

	var mat: StandardMaterial3D
	var phase: float = 0.0
	var _node: Salvage
	var _level: float = LIT
	var _was_spent: bool = false
	## Salvage._strip() knocks a small prop askew and _restore() does not put it back, so a
	## renewable node would lean a little further every cycle. The patch remembers how it was
	## planted and sits back down when it grows in.
	var _base_rot: Vector3
	var _t: float = 0.0
	var _rng := RandomNumberGenerator.new()

	func bind(node: Salvage) -> void:
		_node = node
		_base_rot = rotation
		_rng.randomize()
		_reroll()

	func _reroll() -> void:
		if _node and is_instance_valid(_node):
			_node.yields = {"glow_worm": _rng.randi_range(1, 3)}

	func _process(delta: float) -> void:
		if mat == null:
			return
		_t += delta
		var spent: bool = _node != null and is_instance_valid(_node) and _node.spent
		if spent != _was_spent:
			_was_spent = spent
			if not spent:
				_reroll()   # the patch has grown back: a fresh handful is in it
				rotation = _base_rot
		_level = move_toward(_level, EMBERS if spent else LIT, delta * FADE)
		# The colony breathes even at rest — that slow swell is how you spot one in the dark.
		mat.emission_energy_multiplier = _level * (1.0 + 0.22 * sin(_t * 1.3 + phase))

func _board_visual() -> Node3D:
	var root := Node3D.new()
	var board := MeshInstance3D.new()
	var bm := BoxMesh.new()
	bm.size = Vector3(0.78, 0.05, 0.4)
	bm.material = MatLib.weathered_wood()
	board.mesh = bm
	root.add_child(board)
	board.position = Vector3(0, 0.06, 0)
	# Two trestle blocks under it, and the picked-over remains on top.
	for bx in [-0.28, 0.28]:
		var leg := MeshInstance3D.new()
		var lm := BoxMesh.new()
		lm.size = Vector3(0.08, 0.08, 0.34)
		lm.material = MatLib.weathered_wood()
		leg.mesh = lm
		root.add_child(leg)
		leg.position = Vector3(bx, 0.02, 0)
	for i in range(5):
		var mi := MeshInstance3D.new()
		var cm := CylinderMesh.new()
		cm.top_radius = 0.006
		cm.bottom_radius = 0.009
		cm.height = 0.13 + fmod(i * 0.031, 0.07)
		cm.material = _m_bone
		mi.mesh = cm
		mi.cast_shadow = GeometryInstance3D.SHADOW_CASTING_SETTING_OFF
		root.add_child(mi)
		mi.position = Vector3(-0.18 + i * 0.09, 0.095, fmod(i * 0.07, 0.11) - 0.05)
		mi.rotation.z = deg_to_rad(90.0)
		mi.rotation.y = deg_to_rad(i * 24.0)
	return root
